### ISSUE TITLE
Code issue in page 59

### ISSUE THREAD

**Issue by SharpLu** [PacktPublishing/Apache-Spark-2x-for-Java-Developers#1]
Hi in this book page 59 the example code shows 

Stream<Strings> streamSupplier = .......
   Optional<Integer> simpleSum=
   streamSupplier.map(x->x.length()).reduce((x,y)-> x+y);

but is that stream can directly use the map function? I think they're missing one .get() method

Optional<Integer> simpleSum= streamSupplier.get().map(x->x.length()).reduce((x,y)->x+y);

**Comment by sarvesh-packt** [comment]
Please reopen if the issue still persists.
